#!/usr/bin/env node
/**
 * Writes SITEMAP.md from the code rather than from memory, so the map cannot
 * drift when a section is renamed or a unit is added. Everything below is read
 * off app/page.tsx, data/sessions.ts and public/, never hard-coded.
 *
 * Usage: node scripts/build-sitemap.mjs
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

// data/sessions.ts is TypeScript, so strip the types rather than compile.
// Same approach as scripts/check-coverage.mjs.
const raw = readFileSync(join(root, "data", "sessions.ts"), "utf8");
const stripped = raw
  .replace(/^export type[\s\S]*?};$/gm, "")
  .replace(/:\s*Session\[\]/g, "")
  .replace(/:\s*\{\s*code:[\s\S]*?\}\[\]/g, "")
  .replace(/\(code:\s*string\)/g, "(code)")
  .replace(/^export /gm, "");

const { sessions, unitNames, phases, weeklyUnits } = await import(
  `data:text/javascript,${encodeURIComponent(
    `${stripped}\nexport { sessions, unitNames, phases, weeklyUnits };`,
  )}`
);

const page = readFileSync(join(root, "app", "page.tsx"), "utf8");

// In-page sections, in document order. These anchors are the whole navigation.
const anchors = [...page.matchAll(/<section className="[a-z-]+" id="([a-z-]+)"/g)].map((m) => m[1]);

// Everything the page links out to, deduplicated, ignoring template literals.
const links = [...new Set([...page.matchAll(/href="((?!#)[^"]+)"/g)].map((m) => m[1]))].sort();

const publicRoot = readdirSync(join(root, "public"), { withFileTypes: true })
  .filter((entry) => entry.isFile())
  .map((entry) => entry.name)
  .sort();

const worksheetDir = join(root, "public", "worksheets");
const worksheets = readdirSync(worksheetDir).filter((name) => name.endsWith(".html"));
const sessionSheets = worksheets.filter((name) => /-session-[a-z]\.html$/.test(name));
const warmUpCards = worksheets.filter((name) => /-warm-up-card\.html$/.test(name));
// Grouped rather than listed one by one: twenty-four near-identical filenames
// tell a reader less than a single line saying there is one per unit.
const otherSheets = worksheets
  .filter((name) => !/-session-[a-z]\.html$/.test(name) && !/-warm-up-card\.html$/.test(name))
  .sort();

const missing = sessions
  .map((session) => ({
    id: session.id,
    file: `mathnest-unit-${String(session.unit).padStart(2, "0")}-session-${session.letter.toLowerCase()}.html`,
  }))
  .filter((entry) => !worksheets.includes(entry.file));

const kinds = {};
for (const session of sessions) kinds[session.kind] = (kinds[session.kind] ?? 0) + 1;
const extensions = sessions.filter((session) => !session.expectations?.length).length;

const lines = [];
const put = (text = "") => lines.push(text);

put("# MathNest site map");
put();
put("Generated by `node scripts/build-sitemap.mjs`. Do not edit by hand.");
put();
put(
  "MathNest is a **single-route site**. One rendered page carries the whole application,",
);
put(
  "and every worksheet is a standalone static HTML file linked out from it. There are no",
);
put("nested routes, no dynamic segments, and no API endpoints.");
put();
put("| | |");
put("| --- | --- |");
put(`| Rendered routes | 1 |`);
put(`| In-page sections | ${anchors.length} |`);
put(`| Static HTML pages | ${worksheets.length} |`);
put(`| Parts | ${phases.length} |`);
put(`| Units | ${weeklyUnits.length} |`);
put(`| Sessions | ${sessions.length} |`);
put();

put("## Routes and assets");
put();
put("```");
put("/                                  app/page.tsx, the entire application");
for (const anchor of anchors) put(`  #${anchor}`);
put("");
put("/worksheets/");
put(`  mathnest-unit-NN-session-X.html     ${sessionSheets.length} session exercises`);
put(`  mathnest-unit-NN-warm-up-card.html  ${warmUpCards.length} warm-up cards, one per unit`);
for (const sheet of otherSheets) put(`  ${sheet}`);
put("  mathnest-math-exercises.zip       every exercise in one download");
put("");
put("public/");
for (const file of publicRoot) put(`  ${file}`);
put("```");
put();
put("The Pages build additionally emits `404.html` (the same markup as `index.html`, so an");
put("unknown path renders the app), `CNAME`, and `.nojekyll`. See `scripts/build-pages.mjs`.");
put();

put("## How each static page is reached");
put();
put("| Destination | Linked from | Visible when |");
put("| --- | --- | --- |");
put("| `unit-NN-session-X.html` | Session card, Open worksheet and Download | Its part is selected and its unit is expanded |");
put("| `unit-NN-session-X.html` | Today's lesson card, Open worksheet | Always, but only for the one recommended session |");
put("| `unit-NN-warm-up-card.html` | Weekly rhythm note inside each unit | That unit is expanded |");
put("| `glossary-card.html` | Same idea, two names panel | Parent guide section |");
put("| `math-exercises.zip` | Header, footer, and the no-JavaScript banner | Always |");
put();
put("Outbound targets found in `app/page.tsx`:");
put();
for (const link of links) put(`- \`${link}\``);
put();

put("## Programme tree");
put();
put(
  `${phases.length} parts, ${weeklyUnits.length} units, ${sessions.length} sessions. ` +
    `Session mix is ${Object.entries(kinds).map(([k, v]) => `${v} ${k.toLowerCase()}`).join(", ")}. ` +
    `${extensions} sessions carry no Ontario expectation code; those are the deliberate extensions.`,
);
put();
for (const [index, phase] of phases.entries()) {
  const units = weeklyUnits.slice(index * 4, index * 4 + 4);
  const count = units.reduce((total, unit) => total + unit.sessions.length, 0);
  const first = String(units[0].week).padStart(2, "0");
  const last = String(units[units.length - 1].week).padStart(2, "0");
  put(`### Part ${index + 1}, ${phase.name}`);
  put();
  put(`Units ${first} to ${last}, ${count} sessions. ${phase.note}`);
  put();
  put("| Unit | Focus | Sessions |");
  put("| --- | --- | --- |");
  for (const unit of units) {
    put(
      `| ${String(unit.week).padStart(2, "0")} | ${unitNames[unit.week - 1]} | ${unit.sessions
        .map((session) => session.letter)
        .join(" ")} |`,
    );
  }
  put();
}

put("## Notes");
put();
put(
  missing.length
    ? `- **${missing.length} sessions have no worksheet on disk**: ${missing.map((entry) => entry.id).join(", ")}.`
    : "- Every session resolves to a worksheet that exists on disk. `scripts/check-coverage.mjs` enforces this in CI.",
);
put(
  "- There is no `sitemap.xml` and no `robots.txt`. For a one-route site the crawl benefit " +
    `is small, but the ${worksheets.length} worksheet pages are indexable HTML that nothing currently ` +
    "points a crawler at.",
);
put(
  `- Every unit links to its own warm-up card, ${warmUpCards.length} in total. Unit 01 drills the ` +
    "facts; the rest revisit expectations taught in earlier units, which is the only " +
    "place the programme deliberately returns to old ground.",
);
put(
  "- Anything first taught in the final unit has no later card to appear on, so D2.1 " +
    "and D2.2 are taught once and never revisited. That is the running order, not a gap " +
    "in the schedule.",
);
put();

writeFileSync(join(root, "SITEMAP.md"), `${lines.join("\n")}\n`, "utf8");
console.log(
  `Wrote SITEMAP.md. ${anchors.length} sections, ${worksheets.length} static pages, ${sessions.length} sessions.`,
);
